# Reusable action for retrieving from cache or installing language  dependencies via ASDF
#
# Usage:
# - uses: ./.github/actions/setup

name: Setup and install Elixir & dependencies
description: "Setup and install Elixir & dependencies"

runs:
  using: "composite"
  steps:
  - name: Restore cache of languages from .tool-versions
    uses: actions/cache@v4
    with:
      path: ~/.asdf
      key: ci-asdf-cache-${{ hashFiles('.tool-versions') }}
    id: asdf-cache
  
  - name: Install languages from .tool-versions (if needed)
    uses: asdf-vm/actions/install@v1
    if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}
 
  - name: Install Hex/Rebar (if needed)
    run: mix local.hex --force && mix local.rebar --force
    shell: bash
    if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}
  
  - uses: mbta/actions/reshim-asdf@v1

  - name: Restore cache of Elixir dependencies from mix.lock
    uses: actions/cache@v4
    with:
      path: deps
      key: ci-mix-cache-${{ hashFiles('**/mix.lock') }}
    id: mix-cache
  
  - name: Install Elixir dependencies (if needed)
    if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}
    run: mix deps.get && mix compile
    shell: bash