name: Check PR for problems

on:
  pull_request:

jobs:
  # first job to populate the cache with dependencies
  # the rest of the jobs will run in parallel using the cached dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mix format --check-formatted

  gettext:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mix gettext.extract --check-up-to-date

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mix test.ci

  credo:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: mix credo diff --from-git-merge-base ${{ github.event.pull_request.base.sha }} -a --strict

  dialyzer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mix dialyzer
