name: Check PR for problems

on:
  pull_request:

jobs:
  # first job to populate the cache with dependencies
  # the rest of the jobs will run in parallel using the cached dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix test.ci

  credo:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix credo diff --from-git-merge-base ${{ github.event.pull_request.base.sha }} -a --strict

  dialyzer:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: mix dialyzer

  zizmor:
    name: security / zizmor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          advanced-security: false